### ISSUE TITLE
Auth0 authentication failing from alternative URLs

### ISSUE THREAD

**Issue by nickevansuk** [opensessions/opensessions#13]
The Callback URL for Auth0 should always be the base URL (e.g. https://opensessions-test.imin.co/)

To reproduce this issue, go directly to https://opensessions-test.imin.co/session/add and try to log in.

**Comment by someoneinatree** [comment]
Still no idea why auth0 has this behaviour or cares about this, but auth0 goes off whichever URL the page originally loaded with. This is now tracked and if it isn't root then it reloads the page to root and automatically opens the login dialog. Users shouldn't see this error any more
