### ISSUE TITLE
Send Auth0 userToken over Ajax instead of URL query

### ISSUE THREAD

**Issue by tomoakley** [opensessions/opensessions#4]
Currently the Auth0 token is sent through a URL query when logging in, which makes the URL messy and is probably bad for security reasons. We should be sending it over Ajax instead.

**Comment by someoneinatree** [comment]
To clarify this, I read that cookies may not be a good way to do this as there's domain restrictions that would prevent cookies transferring from the Auth0 side. Hence the tokens are sent in the `location.hash` or in the query string (`location.search`). I'm not sure how the latter protocol works however, as it returns a different kind of code when it activated after I played around with using the `callbackURL` option with `Auth0Lock`.
